-- Oracle Database Syntax
-- Tests Oracle-specific features and syntax

CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID NUMBER(10) PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PHONE_NUMBER VARCHAR2(20),
    HIRE_DATE DATE NOT NULL,
    JOB_ID VARCHAR2(10),
    SALARY NUMBER(8,2),
    COMMISSION_PCT NUMBER(2,2),
    MANAGER_ID NUMBER(10),
    DEPARTMENT_ID NUMBER(4),
    CONSTRAINT FK_EMP_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID NUMBER(4) PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(30) NOT NULL,
    MANAGER_ID NUMBER(10),
    LOCATION_ID NUMBER(4),
    CONSTRAINT FK_DEPT_MGR FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

-- Add missing FK from employees to departments
ALTER TABLE EMPLOYEES ADD CONSTRAINT FK_EMP_DEPT
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID);

CREATE TABLE LOCATIONS (
    LOCATION_ID NUMBER(4) PRIMARY KEY,
    STREET_ADDRESS VARCHAR2(40),
    POSTAL_CODE VARCHAR2(12),
    CITY VARCHAR2(30) NOT NULL,
    STATE_PROVINCE VARCHAR2(25),
    COUNTRY_ID CHAR(2)
);

ALTER TABLE DEPARTMENTS ADD CONSTRAINT FK_DEPT_LOC
    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID);

CREATE TABLE COUNTRIES (
    COUNTRY_ID CHAR(2) PRIMARY KEY,
    COUNTRY_NAME VARCHAR2(40),
    REGION_ID NUMBER
);

ALTER TABLE LOCATIONS ADD CONSTRAINT FK_LOC_COUNTRY
    FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(COUNTRY_ID);

CREATE TABLE REGIONS (
    REGION_ID NUMBER PRIMARY KEY,
    REGION_NAME VARCHAR2(25)
);

ALTER TABLE COUNTRIES ADD CONSTRAINT FK_COUNTRY_REGION
    FOREIGN KEY (REGION_ID) REFERENCES REGIONS(REGION_ID);

CREATE TABLE JOBS (
    JOB_ID VARCHAR2(10) PRIMARY KEY,
    JOB_TITLE VARCHAR2(35) NOT NULL,
    MIN_SALARY NUMBER(8,2),
    MAX_SALARY NUMBER(8,2)
);

ALTER TABLE EMPLOYEES ADD CONSTRAINT FK_EMP_JOB
    FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID);

CREATE TABLE JOB_HISTORY (
    EMPLOYEE_ID NUMBER(10) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    JOB_ID VARCHAR2(10) NOT NULL,
    DEPARTMENT_ID NUMBER(4),
    CONSTRAINT PK_JOB_HISTORY PRIMARY KEY (EMPLOYEE_ID, START_DATE),
    CONSTRAINT FK_JOBHIST_EMP FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
    CONSTRAINT FK_JOBHIST_JOB FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID),
    CONSTRAINT FK_JOBHIST_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID),
    CONSTRAINT CHK_DATES CHECK (END_DATE > START_DATE)
);
